'use client';

import { useState } from 'react';
import { ChevronDown, ShieldCheck, Scale, Send, Clock, CheckCircle2 } from 'lucide-react';
import { LionCapitalEmblem } from '@/components/NationalEmblem';

interface FaqItem {
  id: string;
  question: {
    hi: string;
    en: string;
  };
  answer: {
    hi: string;
    en: string;
  };
  icon: typeof ShieldCheck;
  tag: {
    hi: string;
    en: string;
  };
}

const FAQS: FaqItem[] = [
  {
    id: 'retaliation',
    question: {
      hi: 'क्या शिकायत दर्ज करने पर सरकारी अधिकारी मुझे परेशान कर सकते हैं?',
      en: 'Can government officers harass or retaliate against me for complaining?'
    },
    answer: {
      hi: 'कानूनन नहीं। व्हिसलब्लोअर संरक्षण अधिनियम (Whistle Blowers Protection Act) और नागरिक सुरक्षा संहिता (BNSS) के तहत शिकायतकर्ता को संरक्षण प्राप्त है। NyayaPath द्वारा तैयार अर्जी में विधिक धाराओं का उल्लेख होता है, जिससे अधिकारी पर कानूनी दबाव बनता है। यदि कोई अधिकारी दबाव बनाए, तो विजिलेंस ब्यूरो (सतर्कता आयोग) अथवा लोकायुक्त को तुरंत पूरक शिकायत भेजी जा सकती है।',
      en: 'Legally, no. Complainants are protected under the Whistle Blowers Protection Act and constitutional grievance norms. The legal drafts generated by NyayaPath invoke statutory sections that place legal accountability directly on the public servant. Any retaliatory threat can be immediately reported to the State Vigilance Bureau or Lokayukta.'
    },
    icon: ShieldCheck,
    tag: {
      hi: 'विधिक सुरक्षा',
      en: 'Legal Protection'
    }
  },
  {
    id: 'cost_lawyer',
    question: {
      hi: 'क्या इस अर्जी के लिए मुझे वकील या फीस की जरूरत है?',
      en: 'Do I need to hire a lawyer or pay court fees for this?'
    },
    answer: {
      hi: 'बिल्कुल नहीं। CPGRAMS, जिला मजिस्ट्रेट (DM), विभागीय जांच और सूचना का अधिकार (RTI) में अर्जी देना प्रत्येक नागरिक का मौलिक और विधिक अधिकार है। इसके लिए किसी वकील की आवश्यकता नहीं है। NyayaPath आपकी अर्जी को उसी आधिकारिक कानूनी भाषा में तैयार करता है जैसा कोई वरिष्ठ अधिवक्ता तैयार करता है — 100% नि:शुल्क।',
      en: 'Not at all. Lodging grievances before CPGRAMS, District Magistrates, Departmental Heads, and RTI Authorities is a citizen right requiring zero advocate fees. NyayaPath generates legal notices using formal administrative nomenclature at zero cost.'
    },
    icon: Scale,
    tag: {
      hi: '100% नि:शुल्क',
      en: 'Zero Advocate Fee'
    }
  },
  {
    id: 'where_to_submit',
    question: {
      hi: 'तैयार कानूनी अर्जी को कैसे और कहां जमा करना है?',
      en: 'How and where do I submit the prepared legal application?'
    },
    answer: {
      hi: 'आपके पास 3 सबसे मजबूत तरीके हैं: (1) जन सेवा केंद्र (CSC / Cyber Cafe) से प्रिंट निकालकर संबंधित दफ्तर में व्यक्तिगत रूप से दें और पावती (Receiving / मोहर) लें। (2) डाकघर से रजिस्टर्ड डाक (Speed Post with AD) द्वारा भेजें, जिसकी ट्रैकिंग रसीद कानूनी सबूत होती है। (3) संबंधित सरकारी विभाग के आधिकारिक पोर्टल (जैसे pgportal.gov.in या राज्य जनसुनवाई) पर सीधे कॉपी-पेस्ट करें।',
      en: 'Three most effective channels: (1) Print via Common Service Center (CSC) and submit in person to receive a stamped receiving acknowledgment. (2) Dispatch via Registered Speed Post with Acknowledgment Due (AD)—the postal receipt serves as valid court evidence. (3) Upload directly to official portals (CPGRAMS / State CM Portals).'
    },
    icon: Send,
    tag: {
      hi: 'जमा करने के नियम',
      en: 'Filing Channels'
    }
  },
  {
    id: 'turnaround_time',
    question: {
      hi: 'शिकायत पर सरकारी विभाग को कितने दिनों में कार्रवाई करनी होती है?',
      en: 'How many days does the government department have to take action?'
    },
    answer: {
      hi: 'कार्मिक एवं लोक शिकायत मंत्रालय (DoPT) के नागरिक चार्टर के अनुसार प्रत्येक जन-शिकायत का निवारण अधिकतम 21 से 30 कार्य दिवसों के भीतर अनिवार्य है। साइबर वित्तीय धोखाधड़ी (हेल्पलाइन 1930) में प्रथम 24-48 घंटे निर्णायक होते हैं। यदि 30 दिनों में कार्रवाई नहीं होती, तो न्यायपथ की द्वितीय अपील (L2 Escalation) के जरिए वरिष्ठ सचिव या लोकायुक्त के समक्ष मामला उठाया जा सकता है।',
      en: 'Under the Ministry of Personnel (DoPT) Citizen Charter, public grievances must be resolved within 21 to 30 working days. For cyber financial fraud (1930), the first 24-48 hours are critical. If unresolved within 30 days, the escalation roadmap allows immediate escalation to the Appellate Secretary or Lokayukta.'
    },
    icon: Clock,
    tag: {
      hi: '30 दिन की सीमा',
      en: '30-Day Resolution SLA'
    }
  }
];

export default function CitizenFaq({ lang = 'hi' }: { lang?: string }) {
  const [openId, setOpenId] = useState<string | null>('retaliation');

  const toggleFaq = (id: string) => {
    setOpenId(openId === id ? null : id);
  };

  const isHindi = lang === 'hi';

  return (
    <section className="max-w-4xl mx-auto mt-10 mb-8 px-2 sm:px-4 no-print">
      <div className="p-4 sm:p-6 rounded-2xl bg-white dark:bg-[#081738]/90 border border-slate-200 dark:border-blue-800/60 shadow-md shadow-slate-200/50 dark:shadow-xl dark:shadow-blue-950/40 transition-colors">
        
        {/* HEADER */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-5 border-b border-slate-200 dark:border-blue-900/60 pb-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-50 dark:bg-amber-500/15 border border-amber-300 dark:border-amber-500/40 flex items-center justify-center shrink-0">
              <LionCapitalEmblem className="w-6 h-7 text-amber-500 dark:text-amber-400" fill="#f59e0b" />
            </div>
            <div>
              <h3 className="text-base sm:text-xl font-bold font-indic text-slate-900 dark:text-white flex items-center gap-2">
                <span>{isHindi ? 'नागरिकों के मन में उठने वाले आम सवाल व विधिक अधिकार' : 'Citizen Doubts & Statutory Legal Rights'}</span>
              </h3>
              <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 font-sans">
                {isHindi
                  ? 'सरकारी दफ्तरों के नियम, नि:शुल्क अधिकार और सुरक्षा की पूरी जानकारी (CPGRAMS व NALSA मानक)'
                  : 'Official statutory safeguards, resolution timelines, and filing procedures under Indian law'}
              </p>
            </div>
          </div>
          <span className="text-[11px] sm:text-xs font-semibold px-2.5 py-1 rounded-full bg-emerald-50 dark:bg-emerald-950/70 border border-emerald-200 dark:border-emerald-700/60 text-emerald-800 dark:text-emerald-300 self-start sm:self-center flex items-center gap-1 shadow-2xs">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" />
            <span>{isHindi ? 'सत्यमेव जयते • विधिक रूप से मान्य' : 'Statutorily Valid'}</span>
          </span>
        </div>

        {/* FAQ ACCORDION LIST */}
        <div className="space-y-2.5">
          {FAQS.map((faq) => {
            const isOpen = openId === faq.id;
            const Icon = faq.icon;
            const q = isHindi ? faq.question.hi : faq.question.en;
            const a = isHindi ? faq.answer.hi : faq.answer.en;
            const tag = isHindi ? faq.tag.hi : faq.tag.en;

            return (
              <div
                key={faq.id}
                className={`card-interactive rounded-xl border transition-all duration-200 overflow-hidden ${
                  isOpen
                    ? 'bg-amber-50/40 dark:bg-[#06102a] border-amber-300 dark:border-amber-500/60 shadow-xs dark:shadow-md dark:shadow-blue-950/50'
                    : 'bg-slate-50/80 dark:bg-[#061230]/60 border-slate-200 dark:border-blue-900/60 hover:border-slate-300 dark:hover:border-blue-700/80'
                }`}
              >
                <button
                  type="button"
                  onClick={() => toggleFaq(faq.id)}
                  className="w-full p-3.5 sm:p-4 text-left flex items-center justify-between gap-3 cursor-pointer select-none"
                  aria-expanded={isOpen}
                >
                  <div className="flex items-center gap-2.5 sm:gap-3 min-w-0">
                    <div className={`w-7 h-7 sm:w-8 sm:h-8 rounded-lg flex items-center justify-center shrink-0 ${
                      isOpen 
                        ? 'bg-amber-100 dark:bg-amber-500/20 text-amber-800 dark:text-amber-300 border border-amber-300 dark:border-amber-500/40' 
                        : 'bg-slate-200 dark:bg-blue-950 text-slate-700 dark:text-blue-300 border border-slate-300 dark:border-blue-800'
                    }`}>
                      <Icon className="w-4 h-4" />
                    </div>
                    <div className="min-w-0">
                      <span className="text-xs sm:text-sm font-bold text-slate-900 dark:text-white font-indic block truncate sm:whitespace-normal">
                        {q}
                      </span>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    <span className="hidden sm:inline-block text-[10px] font-semibold px-2 py-0.5 rounded bg-slate-200 dark:bg-blue-950/80 border border-slate-300 dark:border-blue-800/80 text-slate-700 dark:text-blue-300 font-sans">
                      {tag}
                    </span>
                    <ChevronDown
                      className={`w-4 h-4 text-slate-400 dark:text-slate-400 transition-transform duration-200 ${
                        isOpen ? 'rotate-180 text-amber-600 dark:text-amber-400' : ''
                      }`}
                    />
                  </div>
                </button>

                {isOpen && (
                  <div className="px-3.5 sm:px-4 pb-4 pt-1 text-xs sm:text-sm text-slate-700 dark:text-slate-200 font-indic leading-relaxed border-t border-slate-200 dark:border-blue-900/40">
                    <p className="bg-white dark:bg-[#040b1e]/70 p-3 sm:p-3.5 rounded-lg border border-slate-200 dark:border-blue-950 text-slate-700 dark:text-slate-300">
                      {a}
                    </p>
                  </div>
                )}
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
}
